# Generated by Django 5.1.5 on 2026-06-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='card_color',
            field=models.CharField(default='#6c63ff', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
