# Generated by Django 5.1.5 on 2026-06-03 09:05

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_blog_tags_blog_tag1_blog_tag2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tag1', models.TextField()),
                ('tag2', models.TextField()),
                ('tag3', models.TextField()),
                ('card_color', colorfield.fields.ColorField(default='#6c63ff', image_field=None, max_length=25, samples=None)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag2',
            field=models.TextField(),
        ),
    ]
